const photos = [
  {
    id: 1,
    url: "photos/1.jpg",
    description: "Утро",
    likes: 200,
    comments: [
      {
        id: 135,
        avatar: 'img/avatar-6.svg',
        message: 'В целом всё неплохо. Но не всё.',
        name: 'Артём',
      },
      {
        id: 136,
        avatar: 'img/avatar-6.svg',
        message: 'В целом всё неплохо. Но не всё.',
        name: 'Артём',
      },
    ],
  },
  {
    id: 2,
    url: "photos/2.jpg",
    description: "Кот",
    likes: 20,
    comments: [
      {
        id: 13,
        avatar: 'img/avatar-6.svg',
        message: 'В целом всё неплохо. Но не всё.',
        name: 'Артём',
      },
      {
        id: 16,
        avatar: 'img/avatar-6.svg',
        message: 'В целом всё неплохо. Но не всё.',
        name: 'Артём',
      },
    ],
  },
  {
    id: 3,
    url: "photos/3.jpg",
    description: "Собака",
    likes: 150,
    comments: [
      {
        id: 98,
        avatar: 'img/avatar-6.svg',
        message: 'В целом всё неплохо. Но не всё.',
        name: 'Артём',
      },
      {
        id: 1,
        avatar: 'img/avatar-6.svg',
        message: 'В целом всё неплохо. Но не всё.',
        name: 'Артём',
      },
    ],
  }
];
